import art from '@/data/art.json';

// Public-domain Bible illustrations from Wikimedia Commons, indexed by the passage they show.
// Generated by scripts/art (see scripts/art/README.md).
export interface Artwork {
  from: number;
  to: number;
  title: string;
  artist: string;
  year: number;
  src: string;
  width: number;
  height: number;
  page: string;
}

const index = art as Record<string, Record<string, Artwork[]>>;

export function chapterArt(slug: string, chapter: number): Artwork[] {
  return index[slug]?.[chapter] ?? [];
}
